Fill segments using bedtools
LCR-BCCRC/lcr-scripts pull request #28
Opened 2022-03-07 22:05 UTC by Kdreval

This is a different implementation of fill_segments script that is reliant on bedtools. It serves the same goal of filling missing segments in seg files to make them compatible with downstream tools, but this task is achieved using bedtools subtract feature and some perl file modifications.

2022-03-08 01:38 UTC, Kdreval commented on fill_segments/1.0/fill_segments.sh
> +cat $RESULTS_PATH.headerless.bed $RESULTS_PATH.temp | sort -V | perl -pale 'BEGIN { $"="\t"; } $_ = "@F[$#F,0..$#F-1]"' > $RESULTS_PATH.merged.seg
Thanks Jasper! This all has been addressed and pushed to the branch 👍

2022-03-08 02:09 UTC, lkhilton requested changes
I think my only request is that the chromArm.hg19.bed file should actually be called chromArm.grch37.bed for consistency wrt genome_build or projection wildcards. Otherwise looks great! Glad @Jwong684 was able to share his experiences to handle edge cases with you.

2022-03-08 03:03 UTC, Jwong684 approved these changes
Seems like it should work (not sure about the perl parts though)

2022-03-08 04:01 UTC, Kdreval commented
> I think my only request is that the chromArm.hg19.bed file should actually be called chromArm.grch37.bed for consistency wrt genome_build or projection wildcards. Otherwise looks great! Glad @Jwong684 was able to share his experiences to handle edge cases with you.

Thank you, yes the naming was not correct - I updated those files to reflect the proper build 👍

2022-03-09 19:54 UTC, Jwong684 submitted a review, later dismissed

2022-03-11 22:06 UTC, lkhilton approved these changes

2022-03-11 22:09 UTC, merged